### ISSUE TITLE
Django Integration Failed

### ISSUE THREAD

**Issue by yashwanthbabu** [TracyWebTech/django-conversejs#19]
The documentation you have provided was nice and followed the steps as it is. But it doesn't make any sense for me. Apart from integration, using only the script file it works fine as it works in the demo. But while integrating with django it doesnt open the toggle chat and cant able to do anything. 

Did I went with any wrong step for happening this?? Please help

**Comment by fpytloun** [comment]
Hello, you could be interested in this: https://github.com/fpytloun/django-xmpp
It's a little bit different approach than simple Django ConverseJS integration and it ships with newer ConverseJS and code that makes a few XMPP things easier (eg. setting vCard).

**Comment by yashwanthbabu** [comment]
Nope @fpytloun . I have tried that and i found its not I want. But this django-conversejs brings my requirement nearer. I am interested in only this. Main the problem is not loading the javascript initializer template tag in my project {% conversejs_initialize %}. Please kindly provide help regarding this library of how to make an integration  and thanks for your kind reply
