### ISSUE TITLE
context.get('request') is null

### ISSUE THREAD

**Issue by qch1685** [TracyWebTech/django-conversejs#7]
I am a newbie in django. I met some issue in using the django-conversejs. I traced the context.get('request') is null in the function get_conversejs_context.

Can anyone give some some hints? thanks..

================================================
def get_conversejs_context(context, xmpp_login=False):

    context['CONVERSEJS_ENABLED'] = conf.CONVERSEJS_ENABLED
	
	print "get_conversejs_context: CONVERSEJS_ENABLED is " + str(context['CONVERSEJS_ENABLED']);

    if not conf.CONVERSEJS_ENABLED:
        return context

    context.update(conf.get_conversejs_settings())

    request = context.get('request')

    if not xmpp_login or not request.user.is_active:
        return context

======================================================
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/blog/

Django Version: 1.6.2
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polls',
 'blog',
 'conversejs')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Template error:
In template C:\dj_proj\mysite\blog\templates\archive.html, error at line 13
   'NoneType' object has no attribute 'user'
   3 : 

   4 : <!DOCTYPE html>

   5 : <html lang="en">

   6 : <head>

   7 : 

   8 : {% conversejs_static %}

   9 : </head>

   10 : 

   11 : <body>

   12 : {% conversejs_chatpanel %}

   13 :  {% conversejs_initialize %} 

   14 : Testing ...

   15 : 

   16 :  {{ conversejs_static}}

   17 :  

   18 : {% for post in posts %}

   19 : <h2> {{post.title}}</h2>

   20 : <p> {{post.timestamp}}</p>

   21 : <p>{{post.body}}</p>

   22 : {% endfor %}

   23 : 

Traceback:
File "C:\Python27\lib\site-packages\django\core\handlers\base.py" in get_response
  114.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\dj_proj\mysite\blog\views.py" in archive
  11.     return HttpResponse(t.render(c))
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  140.             return self._render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in _render
  134.         return self.nodelist.render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  840.                 bit = self.render_node(node, context)
File "C:\Python27\lib\site-packages\django\template\debug.py" in render_node
  78.             return node.render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  1196.                     _dict = func(*resolved_args, **resolved_kwargs)
File "C:\dj_proj\mysite\conversejs\templatetags\conversejs.py" in conversejs_initialize
  12.     return get_conversejs_context(context, xmpp_login=True)
File "C:\dj_proj\mysite\conversejs\utils.py" in get_conversejs_context
  24.     if not xmpp_login or not request.user.is_active:

Exception Type: AttributeError at /blog/
Exception Value: 'NoneType' object has no attribute 'user'

**Comment by seocam** [comment]
Duplicated of #8.
